<?php
/**
* @file
* A description of what your module does.
*/

/**
 * Implements hook_theme().
 */
function ajax_map_theme($existing, $type, $theme, $path)
{
    return array(
        'ajax_map' => array(
            'variables' => array(
                'var1' => NULL,
                'var2' => NULL,
                'form' => NULL,
            ),
            'template' => 'ajax_map'
        ),
    );
}